feat: start server-manager as internal service
cartesi/rollups-node pull request #175
Opened 2023-11-28 14:04 UTC by torives

Closes #140

2023-11-29 17:27 UTC, gligneul commented on build/docker-compose.yml
> +  build_machine:
Could we rename this to `machine_snapshot_setup`?

2023-11-29 22:15 UTC, gligneul requested changes
Just one minor comment; other than that, it looks good.

2023-11-30 16:40 UTC, GMKrieger approved these changes

2023-11-30 17:59 UTC, gligneul approved these changes

2023-11-30 18:01 UTC, merged