Add read notice commands to rollups-cli
cartesi/rollups-node pull request #186
Opened 2023-12-05 17:18 UTC by GMKrieger

#161

2023-12-05 21:40 UTC, torives reviewed
Looking good. Just left some documentation suggestions 😉

2023-12-06 23:23 UTC, gligneul requested changes

2023-12-11 14:27 UTC, gligneul approved these changes

2023-12-11 18:33 UTC, torives approved these changes

2023-12-11 18:35 UTC, merged