Add read voucher commands to rollups-cli
cartesi/rollups-node pull request #189
Opened 2023-12-05 19:30 UTC by GMKrieger

#164

2023-12-11 19:54 UTC, torives submitted a review, later dismissed

2023-12-12 16:54 UTC, gligneul requested changes

2023-12-12 16:54 UTC, gligneul commented on pkg/readerclient/voucher.go
> +	// Notice index within the context of the input that produced it
```suggestion
	// Voucher index within the context of the input that produced it
```

2023-12-12 16:54 UTC, gligneul commented on pkg/readerclient/voucher.go
> +	// Input whose processing produced the notice
```suggestion
	// Input whose processing produced the voucher
```

2023-12-12 16:54 UTC, gligneul commented on pkg/readerclient/voucher.go
> +	// Notice data as a payload in Ethereum hex binary format, starting with '0x'
```suggestion
	// Voucher data as a payload in Ethereum hex binary format, starting with '0x'
```

2023-12-12 16:54 UTC, gligneul commented on pkg/readerclient/voucher.go
> +	// Proof object that allows this notice to be validated by the base layer blockchain
```suggestion
	// Proof object that allows this voucher to be validated by the base layer blockchain
```

2023-12-12 16:54 UTC, gligneul commented on pkg/readerclient/voucher.go
> +	Destination string `json:"destination"`
This should be either hexutil.Bytes or common.Address

2023-12-12 17:16 UTC, gligneul approved these changes

2023-12-12 17:18 UTC, torives approved these changes

2023-12-12 17:32 UTC, merged