feat: refactor node config
cartesi/rollups-node pull request #327
Opened 2024-02-22 19:31 UTC by fmoura

2024-02-23 11:04 UTC, endersonmaia commented on internal/config/generate/helpers.go
Can't we use templates here? I think it would be easier to grasp how the final go code would look like, instead of building it with helper functions like `addLine` and such.

https://pkg.go.dev/text/template

2024-02-23 11:08 UTC, endersonmaia requested changes

2024-02-23 11:08 UTC, endersonmaia commented on internal/config/validate.go
> +			panic("missing CartesiExperimentalSunodoValidatorRedisEndpoint config")
I think it's better to inform with the format the configuration is defined:

```suggestion
			panic("CARTESI_EXPERIMENTAL_SUNODO_VALIDATOR_REDIS_ENDPOINT environment variable not defined")
```

2024-02-26 19:18 UTC, fmoura commented on internal/config/generate/helpers.go
I will leave this to a new PR. So we can move forward with other PRs that are on top of [PR #318](https://github.com/cartesi/rollups-node/pull/318)

2024-02-27 18:05 UTC, merged