Add input reader repository
cartesi/rollups-node pull request #458
Opened 2024-06-21 14:40 UTC by GMKrieger

#349

2024-06-24 22:19 UTC, fmoura requested changes

2024-06-24 22:19 UTC, fmoura commented on internal/repository/inputreader.go
> +func (pg *database) InsertInputsAndUpdateMostRecentFinalizedBlock(
```suggestion
func (pg *database) InsertInputsAndUpdateMostRecentlyFinalizedBlock(
```

2024-06-25 00:52 UTC, fmoura requested changes

2024-06-25 00:52 UTC, fmoura commented on internal/repository/inputreader.go
> +	inputs []Input,
```suggestion
	inputs []*Input,
```

2024-06-25 00:52 UTC, fmoura commented on internal/repository/inputreader.go
> +	inputs []Input,
Inputs have Blobs, thus can be large

2024-06-25 14:09 UTC, fmoura requested changes

2024-06-25 14:09 UTC, fmoura commented on internal/repository/inputreader.go
> +		return fmt.Errorf("unable to finish empty epoch: %w\n", err)
```suggestion
		return fmt.Errorf("unable to insert inputs: %w\n", err)
```

2024-06-26 01:39 UTC, fmoura requested changes

2024-06-26 01:39 UTC, fmoura commented on internal/repository/inputreader_test.go
> +	response, err := s.database.GetInput(s.ctx, 6)
```suggestion
	response, err := s.database.GetInput(s.ctx, 6)
	s.Require().Nil(err)
```

2024-06-26 01:39 UTC, fmoura commented on internal/repository/inputreader_test.go
> +	response, err := s.database.GetMostRecentBlock(s.ctx)
```suggestion
	response, err := s.database.GetMostRecentBlock(s.ctx)
	s.Require().Nil(err)
```

2024-06-26 02:43 UTC, fmoura commented
When running the `cartesi-rollups-node` for a second time using the same db instance , This error occurs :
```
2024-06-25T23:07:57.250 ERR Unable to run migrations error="no change"
```
This error should be treated differently, as it will happen on a node restart

2024-06-26 16:03 UTC, fmoura submitted a review, later dismissed

2024-06-28 19:30 UTC, fmoura commented on internal/repository/inputreader.go
> +	inputs []*Input,
Here the pointers are more about not copying big structures than using pointer as an "optional" input. Inputs have a `blob []byte` inside.

2024-06-28 19:47 UTC, fmoura commented on internal/repository/inputreader.go
> +	if len(inputs) != 0 {
If you mean the Input part, I agree. But the most recently finalized block can be updated without adding new inputs

2024-07-01 12:56 UTC, GMKrieger commented on internal/repository/inputreader_test.go
The 2 tests that check the most recent finalized block need checks on the database to work. I've created an issue to keep track of this for a future PR. #497 

For now, I will create the first 2 tests for this PR.

2024-07-01 13:52 UTC, fmoura commented
When trying to Setup the database with "actual" values, like `deployment_block = 0x10` I am getting a fk error : 
```
"unable to setup database state: ERROR: insert or update on table \"node_state\" violates foreign key constraint \"node_state_current_epoch_fkey\" (SQLSTATE 23503)\n"
```

I seems it is expecting all epochs from block zero til deployment block to be at the database

2024-07-01 13:54 UTC, torives commented on internal/repository/inputreader.go
> +	inputs []*Input,
The new slice has a reference to the same backing array, so there are no blobs being copied here 😉. [Source](https://go.dev/blog/slices-intro)

2024-07-01 20:01 UTC, GMKrieger commented
> When trying to Setup the database with "actual" values, like `deployment_block = 0x10` I am getting a fk error :
> 
> ```
> "unable to setup database state: ERROR: insert or update on table \"node_state\" violates foreign key constraint \"node_state_current_epoch_fkey\" (SQLSTATE 23503)\n"
> ```
> 
> I seems it is expecting all epochs from block zero til deployment block to be at the database

This error is due to the foreign key of the epoch not being followed. When setting up the database, you have to be sure the first block of the epoch and the current epoch (which on the setup is the deployment block) is the same.

This will change for the next update of the database for the multi-dapp.

2024-07-02 01:36 UTC, fmoura commented on internal/repository/inputreader.go
> +	inputs []*Input,
The Blob itself is a slice. So my main concern do not apply . Thanks

2024-07-03 15:15 UTC, fmoura commented
Got another error while testing. 

Every time the node is started, the Repository Setup function is always adding a new config row, even if it is a node restart ( when the same Postgres instance is the same ) . It should be checked and then just logged

2024-07-03 17:40 UTC, fmoura commented
Also just a comment: 

Using go test coverage during tests, I checked that the tests are not exercising , at the `InsetOutput` method the control flow when a output is not `verifiable`

2024-07-04 15:57 UTC, fmoura commented on internal/repository/inputreader.go
> +	inputs []*Input,
@GMKrieger this suggestion can be accepted. There is no need to use pointers

2024-07-11 19:42 UTC, GMKrieger commented
This PR is deprecated with the release of the multi-dapp repository #511.

2024-07-11 19:42 UTC, closed without merging