fix: Fix eth util tests
cartesi/rollups-node pull request #501
Opened 2024-07-02 19:30 UTC by fmoura

These tests fails sometimes. Now they are adapted to use "Devnet no mining" feature

2024-07-04 19:52 UTC, GMKrieger requested changes
There are overlapping commits between this PR and #500. The way it is now, this PR is redundant as the #500 has both commits.

2024-07-05 17:16 UTC, GMKrieger approved these changes

2024-07-11 18:50 UTC, marcelstanley reviewed
Besides adding a separate commit, we could rephrase the current commit as:
- replace `fix(deps): Update testcontainers usage` with
`fix(tests): update port usage for testcontainers`
- replace`fix(util): Fix ethutil tests` with `fix(tests): mine blocks while adding inputs`

If possible, add more context to them as well

2024-07-11 18:50 UTC, marcelstanley commented on .github/workflows/build.yml
> +          TESTCONTAINERS_RYUK_DISABLED: true
We could move this to a separate commit

2024-07-11 19:29 UTC, marcelstanley approved these changes

2024-07-11 19:31 UTC, merged