Feature/evm reader handle epochs
cartesi/rollups-node pull request #565
Opened 2024-08-15 18:39 UTC by fmoura

2024-08-21 21:49 UTC, fmoura commented on internal/evmreader/evmreader.go
> +	r.epochLengthCache = make(map[Address]uint64)
Epoch's lengths should not change, so the cache is built once per service run

2024-08-21 22:52 UTC, fmoura commented on internal/evmreader/evmreader.go
>  		watchForNewInputsError := r.watchForNewBlocks(ctx, ready)
It was intended to be the same name of the called method. After a few renames, it was not quite right.

Keeping it just `err` as usual is the best way. Thanks

2024-08-22 18:05 UTC, vfusco requested changes

2024-08-22 18:56 UTC, vfusco submitted a review, later dismissed

2024-08-23 14:35 UTC, torives reviewed
Some minor things to fix before the merge:

2024-08-23 14:35 UTC, torives commented on internal/evmreader/evmreader.go
> +// Insert Sort for Inputs into a Input slice
```suggestion
// insertSorted inserts the received input in the slice at the position defined by its index property.
```

2024-08-23 14:35 UTC, torives commented on internal/evmreader/evmreader.go
> +// If includeLastEpoch param tells if the last epoch should be closed or not
```suggestion
// closeEpochs closes all epochs within the given index interval, except for the last.
// If `includeLastEpoch` is true, the last one is included.
```

2024-08-23 14:35 UTC, torives commented on internal/evmreader/retrypolicy/contratfactory.go
> +	// Building a contract do not fail due to network errors.
```suggestion
	// Building a contract does not fail due to network errors.
```

2024-08-23 14:35 UTC, torives commented on internal/evmreader/retrypolicy/contratfactory.go
> +	// Building a contract do not fail due to network errors.
```suggestion
	// Building a contract does not fail due to network errors.
```

2024-08-23 14:36 UTC, fmoura commented on internal/retry/retry.go
> +			slog.Info("Retry Policy: Retrying...", "delay", maxDelay)
We want to know that. It was originally Debug, but became an Info on a previous PR

2024-08-23 14:48 UTC, fmoura commented on internal/evmreader/evmreader.go
> +			"epoch length", epochLength)
Almost the same as above. We want more information when running with "Info" log level. If it really becomes too much we can downgrade it to "Debug" .

The "cached" one makes sense to downgrade.

2024-08-23 15:06 UTC, torives approved these changes

2024-08-23 15:47 UTC, vfusco approved these changes

2024-08-23 15:52 UTC, merged