feat(evm-reader): EVM Reader store only non empty epochs
cartesi/rollups-node pull request #578
Opened 2024-08-26 20:22 UTC by fmoura

2024-08-26 22:23 UTC, vfusco requested changes
Please improve this logic

2024-08-28 14:04 UTC, torives submitted a review, later dismissed

2024-08-28 19:23 UTC, marcelstanley approved these changes

2024-08-28 21:46 UTC, vfusco approved these changes

2024-08-29 01:45 UTC, merged