Feature/advancer repository
cartesi/rollups-node pull request #589
Opened 2024-08-30 21:45 UTC by renan061

2024-09-01 19:18 UTC, fmoura commented on internal/repository/machine.go
> +	// TODO: missing machine config fields
Remove comment. Or am I missing something?

2024-09-03 12:29 UTC, vfusco requested changes

2024-09-03 12:29 UTC, vfusco commented on internal/repository/schema/migrations/000001_create_application_input_claim_output_report_nodeconfig.up.sql
> +    -- Temporary -------------------------------------
Machine config table. And you are missing increment timeouts

2024-09-03 12:29 UTC, vfusco commented on internal/node/model/models.go
> +	MachineInspectTimeout        uint32
Missing increment timeouts. I would follow server-manager config on this.

2024-09-03 17:45 UTC, torives commented on internal/repository/machine.go
> +func toSqlIn[T fmt.Stringer](a []T) string {
This function isn't as generic as its signature implies. I suggest falling back to a single type and renaming it or treat the `model.Address` format before calling it. It would help to add some documentation to it as well.

2024-09-03 17:45 UTC, torives commented on internal/repository/machine.go
> +		return result, nil
Optional: it would be nice to add a WARN log entry here, as this wouldn't be an expected scenario for this function.

2024-09-04 13:54 UTC, fmoura submitted a review, later dismissed

2024-09-04 13:54 UTC, fmoura commented on internal/repository/machine.go
> +func (repo *MachineRepository) UpdateEpochs(ctx context.Context, app Address) error {
```suggestion
func (repo *MachineRepository) UpdateProcessedEpochs(ctx context.Context, app Address) error {
```

2024-09-04 13:54 UTC, fmoura commented on internal/repository/machine.go
> +func (repo *MachineRepository) UpdateEpochs(ctx context.Context, app Address) error {
Or another non too generic name

2024-09-05 21:49 UTC, marcelstanley commented on internal/repository/machine.go
> +func (repo *MachineRepository) UpdateEpochs(ctx context.Context, app Address) error {
+1

2024-09-06 01:42 UTC, marcelstanley commented on internal/repository/machine.go
> +		return nil, fmt.Errorf("%w (failed querying applications): %w", ErrAdvancerRepository, err)
```suggestion
		return nil, fmt.Errorf("%w (failed querying machine configurations): %w", ErrAdvancerRepository, err)
```

2024-09-06 01:42 UTC, marcelstanley commented on internal/repository/machine.go
> +		return nil, fmt.Errorf("%w (failed reading rows): %w", ErrAdvancerRepository, err)
```suggestion
		return nil, fmt.Errorf("%w (failed reading machine configuration rows): %w", ErrAdvancerRepository, err)
```

2024-09-06 01:42 UTC, marcelstanley commented on internal/repository/machine.go
> +    `)
```suggestion
	query := `
        SELECT   id, index, status, raw_data
        FROM     input
        WHERE    application_address = @applicationAddress
        AND      index >= @index
        AND      status != 'NONE'
        ORDER BY index ASC
    `
```

2024-09-06 01:42 UTC, marcelstanley commented on internal/repository/machine.go
> +    `, toSqlIn(apps)) // NOTE: not sanitized
```suggestion
        `, addressesToSqlInValues(apps)) // NOTE: not sanitized
```

2024-09-06 01:42 UTC, marcelstanley commented on internal/repository/machine_test.go
> +	})
What's the plan for the pending tests?

2024-09-06 01:42 UTC, marcelstanley commented on internal/repository/machine.go
> +func toSqlIn[T fmt.Stringer](a []T) string {
And I'd suggest naming it `addressesToSqlInValues`

2024-09-06 01:42 UTC, marcelstanley commented on internal/repository/machine.go
> +
Some documentation for the next few functions would help.

2024-09-27 14:30 UTC, vfusco approved these changes
Merging it as is. We will improve it later.

2024-09-27 14:34 UTC, merged